export const getTechIcon = (tech) => {
    if (!tech) return '•';

    const key = tech.toLowerCase();
    const map = {
        'spring boot': '🌱',
        'java osgi': '🧩',
        java: '☕',
        javascript: '🟨',
        typescript: '🟦',
        'html/css': '🌐',
        reactjs: '⚛️',
        'react.js': '⚛️',
        react: '⚛️',
        nextjs: '⏭️',
        'next.js': '⏭️',
        angular: '🅰️',
        'angular.js': '🅰️',
        kotlin: '🟣',
        flutter: '💙',
        dart: '🎯',
        thymeleaf: '🍃',
        kafka: '🌀',
        'apache kafka': '🌀',
        rabbitmq: '🐇',
        websocket: '🔌',
        'active mq': '📡',
        activemq: '📡',
        'node.js': '🟢',
        'nest.js': '🪺',
        quarkus: '⚡',
        erlang: '📞',
        golang: '🐹',
        'c++17': '➕',
        mongodb: '🍃',
        postgresql: '🐘',
        mysql: '🐬',
        mnesia: '🗂️',
        mssql: '🛢️',
        sqlite: '🗂️',
        redis: '🟥',
        qdrant: '🧭',
        elasticsearch: '🔎',
        aws: '☁️',
        'aws services': '☁️',
        'aws (ec2, ecs/eks, s3, rds)': '☁️',
        'aws s3': '🪣',
        docker: '🐳',
        kubernetes: '⎈',
        jenkins: '🤖',
        'github actions': '⚙️',
        git: '🔧',
        svn: '🗂️',
        graphql: '🔗',
        restful: '🌐',
        'linux (ubuntu/rocky)': '🐧',
        'linux (server simulation)': '🐧',
        linux: '🐧',
        windows: '🪟',
        openai: '🧠',
        'open cv': '📷',
        opencv: '📷',
        'google ml kit': '🤖',
        'tensorflow lite': '🧠',
        osgi: '🧩',
        'c++': '➕',
        'tailwind css': '💨',
        bootstrap: '🅱️',
        mui: '🎨',
        sonarlint: '🔍',
        postman: '📮',
        figma: '🎯',
        dbeaver: '🦫',
        'power bi': '📊',
        'power query': '🧮',
        dax: '📐',
        soapui: '🧼',
        'nvidia deepstream': '🎥',
        triton: '🚀',
        'data lake integration': '🗄️',
        heroku: '🚀',
        'aws s3 ': '🪣',
    };

    return map[key] || '•';
};
