export const getTechIcon = (tech) => {
    if (!tech) return '•';
    const key = tech.toLowerCase();
    const map = {
        'spring boot': '🌱',
        'java osgi': '🧩',
        'java': '☕',
        'javascript': '🟨',
        'typescript': '🟦',
        'html/css': '🌐',
        'reactjs': '⚛️',
        'react': '⚛️',
        'nextjs': '⏭️',
        'angular': '🅰️',
        'kotlin': '🟣',
        'flutter': '💙',
        'dart': '🎯',
        'thymeleaf': '🍃',
        'kafka': '🌀',
        'rabbitmq': '🐇',
        'websocket': '🔌',
        'active mq': '📡',
        'activemq': '📡',
        'mongodb': '🍃',
        'postgresql': '🐘',
        'mysql': '🐬',
        'mssql': '🛢️',
        'sqlite': '🗂️',
        'redis': '🟥',
        'elasticsearch': '🔎',
        'aws': '☁️',
        'aws services': '☁️',
        'aws s3': '🪣',
        'docker': '🐳',
        'kubernetes': '⎈',
        'jenkins': '🤖',
        'git': '🔧',
        'svn': '🗂️',
        'graphql': '🔗',
        'restful': '🌐',
        'linux (ubuntu/rocky)': '🐧',
        'linux': '🐧',
        'windows': '🪟',
        'openai': '🧠',
        'open cv': '📷',
        'opencv': '📷',
        'google ml kit': '🤖',
        'tensorflow lite': '🧠',
        'osgi': '🧩',
        'c++': '➕',
        'heroku': '🚀',
        'aws s3 ': '🪣'
    };
    return map[key] || '•';
};
