const TECH_ICON_MAP = {
    'spring boot': '🌱',
    'java osgi': '🧩',
    java: '☕',
    javascript: '🟨',
    typescript: '🟦',
    'html/css': '🌐',
    reactjs: '⚛️',
    'react.js': '⚛️',
    react: '⚛️',
    nextjs: '⏭️',
    'next.js': '⏭️',
    angular: '🅰️',
    'angular.js': '🅰️',
    angularjs: '🅰️',
    kotlin: '🟣',
    flutter: '💙',
    dart: '🎯',
    thymeleaf: '🍃',
    kafka: '🌀',
    'apache kafka': '🌀',
    rabbitmq: '🐇',
    websocket: '🔌',
    'active mq': '📡',
    activemq: '📡',
    'node.js': '🟢',
    'nest.js': '🪺',
    nestjs: '🪺',
    quarkus: '⚡',
    'java quarkus': '☕⚡',
    erlang: '📞',
    zmq: '🔌',
    golang: '🐹',
    'basic golang': '🐹',
    'c++17': '➕',
    'basic python': '🐍',
    python: '🐍',
    mongodb: '🍃',
    postgresql: '🐘',
    mysql: '🐬',
    mnesia: '🗂️',
    mssql: '🛢️',
    sqlite: '🗂️',
    redis: '🟥',
    qdrant: '🧭',
    elasticsearch: '🔎',
    aws: '☁️',
    'basic aws': '☁️',
    'aws services': '☁️',
    'aws (ec2, ecs/eks, s3, rds)': '☁️',
    'aws s3': '🪣',
    docker: '🐳',
    kubernetes: '⎈',
    jenkins: '🤖',
    'github actions': '⚙️',
    git: '🔧',
    svn: '🗂️',
    graphql: '🔗',
    restful: '🌐',
    'linux (ubuntu/rocky)': '🐧',
    'linux (server simulation)': '🐧',
    linux: '🐧',
    windows: '🪟',
    openai: '🧠',
    'open cv': '📷',
    opencv: '📷',
    'google ml kit': '🤖',
    'tensorflow lite': '🧠',
    osgi: '🧩',
    'c++': '➕',
    'tailwind css': '💨',
    bootstrap: '🅱️',
    mui: '🎨',
    sonarlint: '🔍',
    postman: '📮',
    figma: '🎯',
    dbeaver: '🦫',
    'power bi': '📊',
    'power query': '🧮',
    dax: '📐',
    soapui: '🧼',
    'nvidia deepstream': '🎥',
    'triton inference server': '🚀',
    triton: '🚀',
    gstreamer: '🎬',
    rtsp: '📡',
    'english (intermediate)': '🇬🇧',
    'korean (topik 4)': '🇰🇷',
    'data lake integration': '🗄️',
    heroku: '🚀',
    'aws s3 ': '🪣',
};

export const getTechIcon = (tech) => {
    if (!tech) return '•';
    const key = tech.toLowerCase().trim();
    return TECH_ICON_MAP[key] || '•';
};
